# Generated by Django 4.2.10 on 2024-08-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_web", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="address_1",
            new_name="alamat",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="full_name",
            new_name="nama_lengkap",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="username",
            new_name="nama_pengguna",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="phone",
            new_name="nomor_telepon",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="date_joined",
            new_name="tanggal_daftar",
        ),
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Pria", "Pria"), ("Wanita", "Wanita")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="tanggal_lahir",
            field=models.DateField(blank=True, null=True),
        ),
    ]
