# Generated by Django 4.2.10 on 2024-06-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bayar", "0004_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(default="0"),
        ),
    ]
