# Generated by Django 4.2.10 on 2024-06-22 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bayar", "0005_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="Product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bayar.product",
            ),
        ),
    ]
