# Generated by Django 4.2.10 on 2024-06-24 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bayar", "0006_order_product"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="order",
            table="bayar_order",
        ),
    ]
