# Generated by Django 4.2.10 on 2024-06-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bayar", "0007_alter_order_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
