# Generated by Django 4.2.10 on 2024-06-25 07:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bayar", "0008_alter_order_id"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="order",
            table=None,
        ),
    ]
