# Generated by Django 4.2.10 on 2024-07-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bayar", "0010_remove_product_image_url_product_product_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_images",
            field=models.ImageField(null=True, upload_to="bayar/static/"),
        ),
    ]
