# Generated by Django 4.2.10 on 2024-07-16 09:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("bayar", "0015_alter_order_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="Product",
            new_name="product_id",
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
