# Generated by Django 4.2.10 on 2024-08-01 19:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("bayar", "0016_rename_product_order_product_id_alter_order_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTS",
            fields=[
                (
                    "order_id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now=True)),
                (
                    "price_option",
                    models.DecimalField(
                        choices=[
                            ("Tiket_SD", "25000"),
                            ("Tiket_SMP", "25000"),
                            ("Tiket_SMA", "25000"),
                        ],
                        decimal_places=2,
                        default="Tiket_SD",
                        max_digits=10,
                    ),
                ),
                ("quantity", models.IntegerField(default="1")),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
    ]
