# Generated by Django 4.2.10 on 2024-08-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bayar", "0017_ots"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ots",
            name="price_option",
            field=models.DecimalField(
                choices=[
                    ("Tiket_SD", "Tiket SD"),
                    ("Tiket_SMP", "Tiket SMP"),
                    ("Tiket_SMA", "Tiket SMA"),
                ],
                decimal_places=2,
                default="Tiket_SD",
                max_digits=10,
            ),
        ),
    ]
