# Generated by Django 4.2.10 on 2024-08-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bayar", "0021_alter_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="validated",
            field=models.BooleanField(default=True),
        ),
    ]
